
const stars = [
    {
        id: 1,
        status: false,
        x: 20,
        y: 280,
        width: 80,
        height: 80,
    },
    {
        id: 2,
        status: false,
        x: 30,
        y: 380,
        width: 40,
        height: 40,
    },
    {
        id: 3,
        status: false,
        x: 90,
        y: 360,
        width: 40,
        height: 40,
    },
    {
        id: 4,
        status: false,
        x: 60,
        y: 380,
        width: 40,
        height: 40,
    },
    {
        id: 5,
        status: false,
        x: 90,
        y: 380,
        width: 40,
        height: 40,
    },
    {
        id: 6,
        status: false,
        x: 90,
        y: 490,
        width: 40,
        height: 40,
    },
    {
        id: 7,
        status: false,
        x: 90,
        y: 530,
        width: 40,
        height: 40,
    },
    {
        id: 8,
        status: false,
        x: 110,
        y: 530,
        width: 40,
        height: 40,
    },
    {
        id: 9,
        status: false,
        x: 60,
        y: 530,
        width: 40,
        height: 40,
    },
    {
        id: 10,
        status: false,
        x: 50,
        y: 430,
        width: 40,
        height: 40,
    },
    {
        id: 11,
        status: false,
        x: 70,
        y: 330,
        width: 40,
        height: 40,
    },
    {
        id: 12,
        status: false,
        x: 100,
        y: 330,
        width: 40,
        height: 40,
    },
    {
        id: 13,
        status: false,
        x: 80,
        y: 400,
        width: 40,
        height: 40,
    },
    {
        id: 14,
        status: false,
        x: 80,
        y: 450,
        width: 40,
        height: 40,
    },
    {
        id: 15,
        status: false,
        x: 70,
        y: 480,
        width: 40,
        height: 40,
    },
    {
        id: 16,
        status: false,
        x: 55,
        y: 630,
        width: 40,
        height: 40,
    },
    {
        id: 17,
        status: false,
        x: 55,
        y: 580,
        width: 40,
        height: 40,
    },
    {
        id: 18,
        status: false,
        x: 90,
        y: 590,
        width: 40,
        height: 40,
    },
    {
        id: 19,
        status: false,
        x: 120,
        y: 590,
        width: 40,
        height: 40,
    },
    {
        id: 20,
        status: false,
        x: 120,
        y: 640,
        width: 40,
        height: 40,
    },
    {
        id: 21,
        status: false,
        x: 90,
        y: 640,
        width: 40,
        height: 40,
    },
    {
        id: 22,
        status: false,
        x: 140,
        y: 590,
        width: 40,
        height: 40,
    },
    {
        id: 23,
        status: false,
        x: 130,
        y: 540,
        width: 40,
        height: 40,
    },
    {
        id: 24,
        status: false,
        x: 110,
        y: 440,
        width: 40,
        height: 40,
    },
    {
        id: 25,
        status: false,
        x: 110,
        y: 400,
        width: 40,
        height: 40,
    },
    {
        id: 26,
        status: false,
        x: 120,
        y: 490,
        width: 40,
        height: 40,
    },
    {
        id: 27,
        status: false,
        x: 140,
        y: 390,
        width: 40,
        height: 40,
    },
    {
        id: 28,
        status: false,
        x: 140,
        y: 290,
        width: 40,
        height: 40,
    },
    {
        id: 29,
        status: false,
        x: 140,
        y: 440,
        width: 40,
        height: 40,
    },
    {
        id: 30,
        status: false,
        x: 190,
        y: 340,
        width: 40,
        height: 40,
    },
    {
        id: 31,
        status: false,
        x: 160,
        y: 340,
        width: 40,
        height: 40,
    },
    {
        id: 32,
        status: false,
        x: 140,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 33,
        status: false,
        x: 290,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 34,
        status: false,
        x: 140,
        y: 370,
        width: 35,
        height: 35,
    },
    {
        id: 35,
        status: false,
        x: 240,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 36,
        status: false,
        x: 240,
        y: 540,
        width: 35,
        height: 35,
    },
    {
        id: 37,
        status: false,
        x: 240,
        y: 440,
        width: 35,
        height: 35,
    },
    {
        id: 38,
        status: false,
        x: 450,
        y: 140,
        width: 40,
        height: 40,
    },
    {
        id: 39,
        status: false,
        x: 470,
        y: 150,
        width: 40,
        height: 40,
    },
    {
        id: 40,
        status: false,
        x: 490,
        y: 160,
        width: 40,
        height: 40,
    },
    {
        id: 41,
        status: false,
        x: 590,
        y: 160,
        width: 40,
        height: 40,
    },
    {
        id: 42,
        status: false,
        x: 590,
        y: 190,
        width: 40,
        height: 40,
    },
    {
        id: 43,
        status: false,
        x: 590,
        y: 210,
        width: 40,
        height: 40,
    },
    {
        id: 44,
        status: false,
        x: 390,
        y: 210,
        width: 40,
        height: 40,
    },
    {
        id: 45,
        status: false,
        x: 290,
        y: 210,
        width: 40,
        height: 40,
    },
    {
        id: 46,
        status: false,
        x: 240,
        y: 210,
        width: 40,
        height: 40,
    },
    {
        id: 47,
        status: false,
        x: 270,
        y: 210,
        width: 40,
        height: 40,
    },
    {
        id: 48,
        status: false,
        x: 270,
        y: 250,
        width: 40,
        height: 40,
    },
    {
        id: 49,
        status: false,
        x: 270,
        y: 290,
        width: 40,
        height: 40,
    },
    {
        id: 50,
        status: false,
        x: 250,
        y: 290,
        width: 40,
        height: 40,
    },
    {
        id: 51,
        status: false,
        x: 250,
        y: 390,
        width: 40,
        height: 40,
    },
    {
        id: 52,
        status: false,
        x: 280,
        y: 380,
        width: 40,
        height: 40,
    },
    {
        id: 53,
        status: false,
        x: 180,
        y: 380,
        width: 40,
        height: 40,
    },
    {
        id: 54,
        status: false,
        x: 180,
        y: 480,
        width: 40,
        height: 40,
    },
    {
        id: 55,
        status: false,
        x: 200,
        y: 480,
        width: 40,
        height: 40,
    },
    {
        id: 56,
        status: false,
        x: 230,
        y: 480,
        width: 40,
        height: 40,
    },
    {
        id: 57,
        status: false,
        x: 290,
        y: 480,
        width: 40,
        height: 40,
    },
    {
        id: 58,
        status: false,
        x: 310,
        y: 480,
        width: 40,
        height: 40,
    },
    {
        id: 59,
        status: false,
        x: 310,
        y: 460,
        width: 40,
        height: 40,
    },
    {
        id: 60,
        status: false,
        x: 310,
        y: 180,
        width: 40,
        height: 40,
    },
    {
        id: 61,
        status: false,
        x: 360,
        y: 180,
        width: 40,
        height: 40,
    },
    {
        id: 62,
        status: false,
        x: 360,
        y: 280,
        width: 40,
        height: 40,
    },
    {
        id: 63,
        status: false,
        x: 360,
        y: 320,
        width: 40,
        height: 40,
    },
    {
        id: 64,
        status: false,
        x: 380,
        y: 330,
        width: 40,
        height: 40,
    },
    {
        id: 65,
        status: false,
        x: 390,
        y: 340,
        width: 40,
        height: 40,
    },
    {
        id: 66,
        status: false,
        x: 410,
        y: 340,
        width: 40,
        height: 40,
    },
    {
        id: 67,
        status: false,
        x: 410,
        y: 360,
        width: 40,
        height: 40,
    },
    {
        id: 68,
        status: false,
        x: 320,
        y: 330,
        width: 40,
        height: 40,
    },
    {
        id: 69,
        status: false,
        x: 340,
        y: 330,
        width: 40,
        height: 40,
    },
    {
        id: 70,
        status: false,
        x: 320,
        y: 430,
        width: 40,
        height: 40,
    },
    {
        id: 71,
        status: false,
        x: 280,
        y: 410,
        width: 40,
        height: 40,
    },
    {
        id: 72,
        status: false,
        x: 290,
        y: 420,
        width: 40,
        height: 40,
    },
    {
        id: 73,
        status: false,
        x: 290,
        y: 450,
        width: 40,
        height: 40,
    },
    {
        id: 74,
        status: false,
        x: 260,
        y: 450,
        width: 40,
        height: 40,
    },
]

export default stars;