
const stars = [
    {
        id: 1,
        status: false,
        x: 420,
        y: 0,
        width: 90,
        height: 90,
    },
    {
        id: 2,
        status: false,
        x: 20,
        y: 280,
        width: 90,
        height: 90,
    },
    {
        id: 3,
        status: false,
        x: 515,
        y: 205,
        width: 90,
        height: 90,
    },
    {
        id: 4,
        status: false,
        x: 60,
        y: 380,
        width: 40,
        height: 40,
    },
    {
        id: 5,
        status: false,
        x: 90,
        y: 380,
        width: 35,
        height: 35,
    },
    {
        id: 6,
        status: false,
        x: 90,
        y: 490,
        width: 30,
        height: 30,
    },
    {
        id: 7,
        status: false,
        x: 90,
        y: 530,
        width: 35,
        height: 35,
    },
    {
        id: 8,
        status: false,
        x: 110,
        y: 530,
        width: 35,
        height: 35,
    },
    {
        id: 9,
        status: false,
        x: 60,
        y: 530,
        width: 45,
        height: 45,
    },
    {
        id: 10,
        status: false,
        x: 54,
        y: 430,
        width: 30,
        height: 30,
    },
    {
        id: 11,
        status: false,
        x: 70,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 12,
        status: false,
        x: 100,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 13,
        status: false,
        x: 80,
        y: 400,
        width: 30,
        height: 30,
    },
    {
        id: 14,
        status: false,
        x: 80,
        y: 450,
        width: 35,
        height: 35,
    },
    {
        id: 15,
        status: false,
        x: 70,
        y: 480,
        width: 30,
        height: 30,
    },
    {
        id: 16,
        status: false,
        x: 55,
        y: 630,
        width: 30,
        height: 30,
    },
    {
        id: 17,
        status: false,
        x: 55,
        y: 580,
        width: 30,
        height: 30,
    },
    {
        id: 18,
        status: false,
        x: 90,
        y: 590,
        width: 35,
        height: 35,
    },
    {
        id: 19,
        status: false,
        x: 120,
        y: 590,
        width: 30,
        height: 30,
    },
    {
        id: 20,
        status: false,
        x: 120,
        y: 640,
        width: 30,
        height: 30,
    },
    {
        id: 21,
        status: false,
        x: 90,
        y: 640,
        width: 35,
        height: 35,
    },
    {
        id: 22,
        status: false,
        x: 140,
        y: 590,
        width: 35,
        height: 35,
    },
    {
        id: 23,
        status: false,
        x: 130,
        y: 540,
        width: 35,
        height: 35,
    },
    {
        id: 24,
        status: false,
        x: 110,
        y: 440,
        width: 30,
        height: 30,
    },
    {
        id: 25,
        status: false,
        x: 110,
        y: 400,
        width: 30,
        height: 30,
    },
    {
        id: 26,
        status: false,
        x: 120,
        y: 490,
        width: 30,
        height: 30,
    },
    {
        id: 27,
        status: false,
        x: 140,
        y: 390,
        width: 30,
        height: 30,
    },
    {
        id: 28,
        status: false,
        x: 140,
        y: 290,
        width: 30,
        height: 30,
    },
    {
        id: 29,
        status: false,
        x: 140,
        y: 440,
        width: 30,
        height: 30,
    },
    {
        id: 30,
        status: false,
        x: 190,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 31,
        status: false,
        x: 160,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 32,
        status: false,
        x: 140,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 33,
        status: false,
        x: 290,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 34,
        status: false,
        x: 140,
        y: 370,
        width: 35,
        height: 35,
    },
    {
        id: 35,
        status: false,
        x: 240,
        y: 340,
        width: 35,
        height: 35,
    },
    {
        id: 36,
        status: false,
        x: 240,
        y: 540,
        width: 35,
        height: 35,
    },
    {
        id: 37,
        status: false,
        x: 240,
        y: 440,
        width: 35,
        height: 35,
    },
    {
        id: 38,
        status: false,
        x: 450,
        y: 140,
        width: 35,
        height: 35,
    },
    {
        id: 39,
        status: false,
        x: 470,
        y: 150,
        width: 35,
        height: 35,
    },
    {
        id: 40,
        status: false,
        x: 490,
        y: 160,
        width: 35,
        height: 35,
    },
    {
        id: 41,
        status: false,
        x: 590,
        y: 160,
        width: 35,
        height: 35,
    },
    {
        id: 42,
        status: false,
        x: 590,
        y: 190,
        width: 35,
        height: 35,
    },
    {
        id: 43,
        status: false,
        x: 590,
        y: 210,
        width: 35,
        height: 35,
    },
    {
        id: 44,
        status: false,
        x: 390,
        y: 210,
        width: 35,
        height: 35,
    },
    {
        id: 45,
        status: false,
        x: 290,
        y: 210,
        width: 35,
        height: 35,
    },
    {
        id: 46,
        status: false,
        x: 240,
        y: 210,
        width: 35,
        height: 35,
    },
    {
        id: 47,
        status: false,
        x: 270,
        y: 210,
        width: 35,
        height: 35,
    },
    {
        id: 48,
        status: false,
        x: 270,
        y: 250,
        width: 35,
        height: 35,
    },
    {
        id: 49,
        status: false,
        x: 270,
        y: 290,
        width: 35,
        height: 35,
    },
    {
        id: 50,
        status: false,
        x: 250,
        y: 290,
        width: 35,
        height: 35,
    },
    {
        id: 51,
        status: false,
        x: 250,
        y: 390,
        width: 35,
        height: 35,
    },
    {
        id: 52,
        status: false,
        x: 280,
        y: 380,
        width: 35,
        height: 35,
    },
    {
        id: 53,
        status: false,
        x: 180,
        y: 380,
        width: 35,
        height: 35,
    },
    {
        id: 54,
        status: false,
        x: 180,
        y: 480,
        width: 35,
        height: 35,
    },
    {
        id: 55,
        status: false,
        x: 200,
        y: 480,
        width: 30,
        height: 30,
    },
    {
        id: 56,
        status: false,
        x: 230,
        y: 480,
        width: 30,
        height: 30,
    },
    {
        id: 57,
        status: false,
        x: 290,
        y: 480,
        width: 30,
        height: 30,
    },
    {
        id: 58,
        status: false,
        x: 310,
        y: 480,
        width: 30,
        height: 30,
    },
    {
        id: 59,
        status: false,
        x: 310,
        y: 460,
        width: 30,
        height: 30,
    },
    {
        id: 60,
        status: false,
        x: 310,
        y: 180,
        width: 30,
        height: 30,
    },
    {
        id: 61,
        status: false,
        x: 360,
        y: 180,
        width: 30,
        height: 30,
    },
    {
        id: 62,
        status: false,
        x: 360,
        y: 280,
        width: 30,
        height: 30,
    },
    {
        id: 63,
        status: false,
        x: 360,
        y: 320,
        width: 30,
        height: 30,
    },
    {
        id: 64,
        status: false,
        x: 380,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 65,
        status: false,
        x: 390,
        y: 340,
        width: 30,
        height: 30,
    },
    {
        id: 66,
        status: false,
        x: 410,
        y: 340,
        width: 30,
        height: 30,
    },
    {
        id: 67,
        status: false,
        x: 410,
        y: 360,
        width: 30,
        height: 30,
    },
    {
        id: 68,
        status: false,
        x: 320,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 69,
        status: false,
        x: 340,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 70,
        status: false,
        x: 320,
        y: 430,
        width: 30,
        height: 30,
    },
    {
        id: 71,
        status: false,
        x: 280,
        y: 410,
        width: 30,
        height: 30,
    },
    {
        id: 72,
        status: false,
        x: 290,
        y: 420,
        width: 30,
        height: 30,
    },
    {
        id: 73,
        status: false,
        x: 290,
        y: 450,
        width: 30,
        height: 30,
    },
    {
        id: 74,
        status: false,
        x: 260,
        y: 450,
        width: 30,
        height: 30,
    },
    {
        id: 74,
        status: false,
        x: 135,
        y: 500,
        width: 60,
        height: 60,
    },
    {
        id: 74,
        status: false,
        x: 135,
        y: 480,
        width: 30,
        height: 30,
    },
    {
        id: 75,
        status: false,
        x: 135,
        y: 460,
        width: 30,
        height: 30,
    },
    {
        id: 76,
        status: false,
        x: 330,
        y: 490,
        width: 50,
        height: 50,
    },
    {
        id: 77,
        status: false,
        x: 330,
        y: 360,
        width: 55,
        height: 55,
    },
    {
        id: 78,
        status: false,
        x: 230,
        y: 360,
        width: 55,
        height: 55,
    },
    {
        id: 79,
        status: false,
        x: 210,
        y: 340,
        width: 30,
        height: 30,
    },
    {
        id: 80,
        status: false,
        x: 320,
        y: 240,
        width: 30,
        height: 30,
    },
    {
        id: 81,
        status: false,
        x: 320,
        y: 260,
        width: 30,
        height: 30,
    },
    {
        id: 82,
        status: false,
        x: 330,
        y: 280,
        width: 35,
        height: 35,
    },
    {
        id: 83,
        status: false,
        x: 300,
        y: 280,
        width: 30,
        height: 30,
    },
    {
        id: 84,
        status: false,
        x: 300,
        y: 320,
        width: 30,
        height: 30,
    },
    {
        id: 85,
        status: false,
        x: 250,
        y: 320,
        width: 30,
        height: 30,
    },
    {
        id: 86,
        status: false,
        x: 225,
        y: 150,
        width: 55,
        height: 55,
    },
    {
        id: 87,
        status: false,
        x: 260,
        y: 190,
        width: 30,
        height: 30,
    },
    {
        id: 88,
        status: false,
        x: 330,
        y: 190,
        width: 30,
        height: 30,
    },
    {
        id: 89,
        status: false,
        x: 330,
        y: 220,
        width: 30,
        height: 30,
    },
    {
        id: 90,
        status: false,
        x: 370,
        y: 220,
        width: 30,
        height: 30,
    },
    {
        id: 91,
        status: false,
        x: 400,
        y: 250,
        width: 30,
        height: 30,
    },
    {
        id: 92,
        status: false,
        x: 400,
        y: 180,
        width: 30,
        height: 30,
    },
    {
        id: 93,
        status: false,
        x: 430,
        y: 180,
        width: 30,
        height: 30,
    },
    {
        id: 94,
        status: false,
        x: 435,
        y: 200,
        width: 30,
        height: 30,
    },
    {
        id: 95,
        status: false,
        x: 455,
        y: 200,
        width: 30,
        height: 30,
    },
    {
        id: 96,
        status: false,
        x: 479,
        y: 200,
        width: 30,
        height: 30,
    },
    {
        id: 97,
        status: false,
        x: 479,
        y: 230,
        width: 30,
        height: 30,
    },
    {
        id: 98,
        status: false,
        x: 479,
        y: 250,
        width: 30,
        height: 30,
    },
    {
        id: 99,
        status: false,
        x: 460,
        y: 270,
        width: 30,
        height: 30,
    },
    {
        id: 100,
        status: false,
        x: 460,
        y: 230,
        width: 35,
        height: 35,
    },
    {
        id: 101,
        status: false,
        x: 460,
        y: 290,
        width: 35,
        height: 35,
    },
    {
        id: 102,
        status: false,
        x: 460,
        y: 320,
        width: 35,
        height: 35,
    },
    {
        id: 103,
        status: false,
        x: 480,
        y: 320,
        width: 35,
        height: 35,
    },
    {
        id: 104,
        status: false,
        x: 490,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 105,
        status: false,
        x: 530,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 106,
        status: false,
        x: 530,
        y: 360,
        width: 30,
        height: 30,
    },
    {
        id: 107,
        status: false,
        x: 530,
        y: 360,
        width: 60,
        height: 60,
    },
    {
        id: 108,
        status: false,
        x: 430,
        y: 350,
        width: 35,
        height: 35,
    },
    {
        id: 109,
        status: false,
        x: 330,
        y: 350,
        width: 35,
        height: 35,
    },
    {
        id: 110,
        status: false,
        x: 300,
        y: 370,
        width: 35,
        height: 35,
    },
    {
        id: 111,
        status: false,
        x: 300,
        y: 400,
        width: 35,
        height: 35,
    },
    {
        id: 112,
        status: false,
        x: 260,
        y: 500,
        width: 35,
        height: 35,
    },
    {
        id: 113,
        status: false,
        x: 260,
        y: 470,
        width: 30,
        height: 30,
    },
    {
        id: 114,
        status: false,
        x: 500,
        y: 350,
        width: 30,
        height: 30,
    },
    {
        id: 115,
        status: false,
        x: 500,
        y: 300,
        width: 30,
        height: 30,
    },
    {
        id: 116,
        status: false,
        x: 480,
        y: 280,
        width: 30,
        height: 30,
    },
    {
        id: 117,
        status: false,
        x: 520,
        y: 280,
        width: 30,
        height: 30,
    },
    {
        id: 118,
        status: false,
        x: 540,
        y: 280,
        width: 30,
        height: 30,
    },
    {
        id: 119,
        status: false,
        x: 540,
        y: 200,
        width: 30,
        height: 30,
    },
    {
        id: 120,
        status: false,
        x: 500,
        y: 205,
        width: 30,
        height: 30,
    },
    {
        id: 121,
        status: false,
        x: 507,
        y: 230,
        width: 40,
        height: 40,
    },
    {
        id: 122,
        status: false,
        x: 507,
        y: 180,
        width: 40,
        height: 40,
    },
    {
        id: 123,
        status: false,
        x: 507,
        y: 150,
        width: 30,
        height: 30,
    },
    {
        id: 124,
        status: false,
        x: 507,
        y: 120,
        width: 30,
        height: 30,
    },
    {
        id: 125,
        status: false,
        x: 480,
        y: 100,
        width: 30,
        height: 30,
    },
    {
        id: 126,
        status: false,
        x: 460,
        y: 100,
        width: 30,
        height: 30,
    },
    {
        id: 127,
        status: false,
        x: 470,
        y: 130,
        width: 35,
        height: 35,
    },
    {
        id: 128,
        status: false,
        x: 470,
        y: 70,
        width: 35,
        height: 35,
    },
    {
        id: 129,
        status: false,
        x: 490,
        y: 70,
        width: 35,
        height: 35,
    },
    {
        id: 130,
        status: false,
        x: 490,
        y: 50,
        width: 30,
        height: 30,
    },
    {
        id: 131,
        status: false,
        x: 530,
        y: 50,
        width: 30,
        height: 30,
    },
    {
        id: 132,
        status: false,
        x: 540,
        y: 74,
        width: 55,
        height: 55,
    },
    {
        id: 133,
        status: false,
        x: 534,
        y: 98,
        width: 30,
        height: 30,
    },
    {
        id: 134,
        status: false,
        x: 534,
        y: 120,
        width: 30,
        height: 30,
    },
    {
        id: 135,
        status: false,
        x: 530,
        y: 140,
        width: 30,
        height: 30,
    },
    {
        id: 136,
        status: false,
        x: 530,
        y: 160,
        width: 40,
        height: 40,
    },
    {
        id: 137,
        status: false,
        x: 580,
        y: 74,
        width: 35,
        height: 35,
    },
    {
        id: 138,
        status: false,
        x: 590,
        y: 63,
        width: 30,
        height: 30,
    },
    {
        id: 139,
        status: false,
        x: 640,
        y: 63,
        width: 30,
        height: 30,
    },
    {
        id: 140,
        status: false,
        x: 624,
        y: 44,
        width: 30,
        height: 30,
    },
    {
        id: 141,
        status: false,
        x: 650,
        y: 44,
        width: 30,
        height: 30,
    },
    {
        id: 142,
        status: false,
        x: 670,
        y: 44,
        width: 30,
        height: 30,
    },
    {
        id: 143,
        status: false,
        x: 700,
        y: 79,
        width: 30,
        height: 30,
    },
    {
        id: 144,
        status: false,
        x: 700,
        y: 30,
        width: 45,
        height: 45,
    },
    {
        id: 145,
        status: false,
        x: 600,
        y: 30,
        width: 35,
        height: 35,
    },
    {
        id: 146,
        status: false,
        x: 570,
        y: 30,
        width: 35,
        height: 35,
    },
    {
        id: 147,
        status: false,
        x: 650,
        y: 180,
        width: 30,
        height: 30,
    },
    {
        id: 148,
        status: false,
        x: 640,
        y: 198,
        width: 30,
        height: 30,
    },
    {
        id: 149,
        status: false,
        x: 623,
        y: 198,
        width: 30,
        height: 30,
    },
    {
        id: 150,
        status: false,
        x: 623,
        y: 224,
        width: 40,
        height: 40,
    },
    {
        id: 151,
        status: false,
        x: 650,
        y: 224,
        width: 40,
        height: 40,
    },
    {
        id: 152,
        status: false,
        x: 670,
        y: 200,
        width: 30,
        height: 30,
    },
    {
        id: 153,
        status: false,
        x: 670,
        y: 220,
        width: 30,
        height: 30,
    },
    {
        id: 154,
        status: false,
        x: 560,
        y: 200,
        width: 30,
        height: 30,
    },
    {
        id: 155,
        status: false,
        x: 555,
        y: 175,
        width: 30,
        height: 30,
    },
    {
        id: 156,
        status: false,
        x: 555,
        y: 55,
        width: 30,
        height: 30,
    },
    {
        id: 157,
        status: false,
        x: 536,
        y: 30,
        width: 30,
        height: 30,
    },
    {
        id: 158,
        status: false,
        x: 499,
        y: 30,
        width: 30,
        height: 30,
    },
    {
        id: 159,
        status: false,
        x: 510,
        y: 80,
        width: 35,
        height: 35,
    },
    {
        id: 160,
        status: false,
        x: 610,
        y: 80,
        width: 35,
        height: 35,
    },
    {
        id: 161,
        status: false,
        x: 640,
        y: 80,
        width: 45,
        height: 45,
    },
    {
        id: 162,
        status: false,
        x: 660,
        y: 76,
        width: 35,
        height: 35,
    },
    {
        id: 163,
        status: false,
        x: 435,
        y: 150,
        width: 50,
        height: 50,
    },
    {
        id: 164,
        status: false,
        x: 420,
        y: 220,
        width: 60,
        height: 60,
    },
    {
        id: 165,
        status: false,
        x: 330,
        y: 290,
        width: 60,
        height: 60,
    },
    {
        id: 166,
        status: false,
        x: 270,
        y: 330,
        width: 30,
        height: 30,
    },
    {
        id: 167,
        status: false,
        x: 250,
        y: 260,
        width: 30,
        height: 30,
    },
    {
        id: 168,
        status: false,
        x: 250,
        y: 235,
        width: 30,
        height: 30,
    },
    {
        id: 169,
        status: false,
        x: 200,
        y: 320,
        width: 30,
        height: 30,
    },
    {
        id: 170,
        status: false,
        x: 180,
        y: 320,
        width: 30,
        height: 30,
    },
    {
        id: 171,
        status: false,
        x: 160,
        y: 325,
        width: 30,
        height: 30,
    },
    {
        id: 172,
        status: false,
        x: 140,
        y: 315,
        width: 30,
        height: 30,
    },
    {
        id: 173,
        status: false,
        x: 120,
        y: 334,
        width: 30,
        height: 30,
    },
    {
        id: 174,
        status: false,
        x: 120,
        y: 360,
        width: 30,
        height: 30,
    },
    {
        id: 175,
        status: false,
        x: 104,
        y: 362,
        width: 30,
        height: 30,
    },
    {
        id: 176,
        status: false,
        x: 88,
        y: 362,
        width: 30,
        height: 30,
    },
    {
        id: 177,
        status: false,
        x: 60,
        y: 362,
        width: 30,
        height: 30,
    },
    {
        id: 178,
        status: false,
        x: 60,
        y: 410,
        width: 30,
        height: 30,
    },
    {
        id: 179,
        status: false,
        x: 80,
        y: 423,
        width: 30,
        height: 30,
    },
    {
        id: 180,
        status: false,
        x: 103,
        y: 423,
        width: 30,
        height: 30,
    },
    {
        id: 181,
        status: false,
        x: 128,
        y: 423,
        width: 30,
        height: 30,
    },
    {
        id: 182,
        status: false,
        x: 128,
        y: 612,
        width: 30,
        height: 30,
    },
    {
        id: 183,
        status: false,
        x: 100,
        y: 612,
        width: 30,
        height: 30,
    },
    {
        id: 184,
        status: false,
        x: 80,
        y: 612,
        width: 30,
        height: 30,
    },
    {
        id: 185,
        status: false,
        x: 60,
        y: 648,
        width: 30,
        height: 30,
    },
    {
        id: 186,
        status: false,
        x: 80,
        y: 570,
        width: 30,
        height: 30,
    },
    {
        id: 187,
        status: false,
        x: 109,
        y: 570,
        width: 30,
        height: 30,
    },
    {
        id: 188,
        status: false,
        x: 109,
        y: 505,
        width: 30,
        height: 30,
    },
    {
        id: 189,
        status: false,
        x: 80,
        y: 505,
        width: 30,
        height: 30,
    },
    {
        id: 190,
        status: false,
        x: 90,
        y: 470,
        width: 30,
        height: 30,
    },
    {
        id: 191,
        status: false,
        x: 105,
        y: 470,
        width: 30,
        height: 30,
    },
    {
        id: 192,
        status: false,
        x: 165,
        y: 470,
        width: 30,
        height: 30,
    },
    {
        id: 193,
        status: false,
        x: 180,
        y: 500,
        width: 40,
        height: 40,
    },
    {
        id: 194,
        status: false,
        x: 210,
        y: 500,
        width: 40,
        height: 40,
    },
    {
        id: 195,
        status: false,
        x: 210,
        y: 460,
        width: 40,
        height: 40,
    },
    {
        id: 196,
        status: false,
        x: 183,
        y: 454,
        width: 40,
        height: 40,
    },
    {
        id: 197,
        status: false,
        x: 260,
        y: 486,
        width: 30,
        height: 30,
    },
    {
        id: 198,
        status: false,
        x: 303,
        y: 498,
        width: 30,
        height: 30,
    },
    {
        id: 199,
        status: false,
        x: 303,
        y: 250,
        width: 30,
        height: 30,
    },
    {
        id: 200,
        status: false,
        x: 303,
        y: 305,
        width: 30,
        height: 30,
    },
    {
        id: 201,
        status: false,
        x: 280,
        y: 180,
        width: 30,
        height: 30,
    },
    {
        id: 202,
        status: false,
        x: 280,
        y: 230,
        width: 30,
        height: 30,
    },
    {
        id: 203,
        status: false,
        x: 280,
        y: 270,
        width: 30,
        height: 30,
    },
    {
        id: 204,
        status: false,
        x: 280,
        y: 310,
        width: 30,
        height: 30,
    },
    {
        id: 205,
        status: false,
        x: 272,
        y: 350,
        width: 30,
        height: 30,
    },
    {
        id: 206,
        status: false,
        x: 370,
        y: 350,
        width: 30,
        height: 30,
    },
    {
        id: 207,
        status: false,
        x: 430,
        y: 320,
        width: 30,
        height: 30,
    },
    {
        id: 208,
        status: false,
        x: 460,
        y: 340,
        width: 30,
        height: 30,
    },
    {
        id: 209,
        status: false,
        x: 460,
        y: 360,
        width: 30,
        height: 30,
    },
    {
        id: 210,
        status: false,
        x:335,
        y: 460,
        width: 30,
        height: 30,
    },
    {
        id: 211,
        status: false,
        x:335,
        y: 410,
        width: 30,
        height: 30,
    },
    {
        id: 212,
        status: false,
        x:520,
        y: 300,
        width: 30,
        height: 30,
    },
    {
        id: 213,
        status: false,
        x:500,
        y: 270,
        width: 30,
        height: 30,
    },
    {
        id: 214,
        status: false,
        x:600,
        y: 230,
        width: 30,
        height: 30,
    },
    {
        id: 215,
        status: false,
        x:620,
        y: 180,
        width: 30,
        height: 30,
    },
]


export default stars;